CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL, -- Type of event (e.g., 'Create', 'Delete')
    TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL,
    CLIENT_ID VARCHAR(255) NOT NULL,
    ADMIN_ID INT NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES USERS(CLIENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID) ON DELETE CASCADE
);

