CREATE TABLE ADMIN IF NOT EXISTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ENTITY_ID VARCHAR(255) NOT NULL UNIQUE,
    MASTER_TOKEN VARCHAR(255) NOT NULL
);

INSERT INTO ADMIN VALUES (1, "Entity1", "supersecrettoken1");
INSERT INTO ADMIN VALUES (2, "Entity2", "supersecrettoken2");
INSERT INTO ADMIN VALUES (3, "Entity3", "supersecrettoken3");