CREATE TABLE USERS IF NOT EXISTS (
    CLIENT_ID VARCHAR(255) PRIMARY KEY AUTO_INCREMENT,
    ACCESS_TOKEN VARCHAR(255) NOT NULL,
    ROLE TEXT NOT NULL,
    EXPIRY TIMESTAMP NOT NULL,


    FOREIGN KEY (CLIENT_ID) REFERENCES ADMIN(MASTER_TOKEN),
);

/* With this setup users will remain logged in for one day and mods for one week*/
INSERT INTO USERS VALUES ("User1", "supersecrettoken1", "USER", TIMESTAMP(NOW(), INTERVAL 24 HOUR));
INSERT INTO USERS VALUES ("Bill Gates", "supersecrettoken2", "PREMIUM_USER", TIMESTAMP(NOW(), INTERVAL 24 HOUR));
INSERT INTO USERS VALUES ("Linus Torvald", "supersecrettoken3", "MODERATOR", TIMESTAMP(NOW(), INTERVAL 7 DAY));
