USE OAuthSystem;

DROP TABLE USERS;

CREATE TABLE USERS (
	CLIENT_ID VARCHAR(255) NOT NULL,
    ACCESS_TOKEN VARCHAR(255) NOT NULL PRIMARY KEY,
    ROLE TEXT NOT NULL,
    EXPIRY TIMESTAMP NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES ADMIN(ENTITY_ID)
);

/* With this setup users will remain logged in for one day and mods for one week*/
INSERT INTO USERS VALUES ("Entity1", "supersecrettoken1", "USER", TIMESTAMP(NOW() + INTERVAL 24 HOUR));
INSERT INTO USERS VALUES ("Entity1", "supersecrettoken2", "PREMIUM_USER", TIMESTAMP(NOW() + INTERVAL 24 HOUR));
INSERT INTO USERS VALUES ("Entity1", "supersecrettoken3", "MODERATOR", TIMESTAMP(NOW() + INTERVAL 7 DAY));

SELECT * FROM USERS;