DELIMITER //

CREATE TRIGGER log_token_creation
AFTER INSERT ON USERS
FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_LOG (EVENT_TYPE, CLIENT_ID, ADMIN_ID)
  VALUES ('CREATE', NEW.CLIENT_ID, NEW.ADMIN_ID);
END; //

DELIMITER ;