CREATE OR REPLACE VIEW `TOKEN_AUDIT_LOG_VIEW` AS
SELECT
  A.`ID`,
  A.`EVENT_TYPE`,
  A.`TIMESTAMP`   AS event_ts, 
  U.`CLIENT_ID`,
  U.`ROLE`,
  AD.`ENTITY_ID`
FROM `AUDIT_LOG` A
  JOIN `USERS` U
    ON A.`CLIENT_ID` = U.`CLIENT_ID`
  JOIN `ADMIN` AD
    ON A.`ADMIN_ID` = AD.`ID`;     
