-- The view selects the ID, EVENT_TYPE, TIMESTAMP from AUDIT_LOG, CLIENT_ID and ROLE from USERS, and ENTITY_ID from ADMIN
CREATE OR REPLACE VIEW TOKEN_AUDIT_LOG_VIEW AS
SELECT A.ID, A.EVENT_TYPE, A.TIMESTAMP, U.CLIENT_ID, U.ROLE, AD.ENTITY_ID
FROM AUDIT_LOG A
JOIN USERS U ON A.CLIENT_ID = U.CLIENT_ID
JOIN ADMIN AD ON A.ADMIN_ID = AD.ID;